version: '3'
services:
  db:
    container_name: first-db-container
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: first_db
      POSTGRES_USER: first_user
      POSTGRES_PASSWORD: root
  web:
    container_name: first-web-container
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/first_db
      SPRING_DATASOURCE_USERNAME: first_user
      SPRING_DATASOURCE_PASSWORD: root